import { Account, Transaction, Budget, TransactionCategory } from '../types';

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Primary Checking',
    type: 'checking',
    balance: 12543.28,
    lastUpdated: new Date('2025-11-19'),
  },
  {
    id: '2',
    name: 'High Yield Savings',
    type: 'savings',
    balance: 45230.67,
    lastUpdated: new Date('2025-11-19'),
  },
  {
    id: '3',
    name: 'Credit Card',
    type: 'credit',
    balance: -2341.52,
    lastUpdated: new Date('2025-11-18'),
  },
  {
    id: '4',
    name: 'Investment Account',
    type: 'investment',
    balance: 128456.93,
    lastUpdated: new Date('2025-11-18'),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-19'),
    description: 'Whole Foods Market',
    category: 'Groceries',
    amount: -127.43,
    type: 'debit',
  },
  {
    id: '2',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-18'),
    description: 'Payroll Deposit',
    category: 'Income',
    amount: 3250.00,
    type: 'credit',
  },
  {
    id: '3',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-18'),
    description: 'Amazon Purchase',
    category: 'Shopping',
    amount: -89.99,
    type: 'debit',
  },
  {
    id: '4',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-17'),
    description: 'Shell Gas Station',
    category: 'Transportation',
    amount: -52.34,
    type: 'debit',
  },
  {
    id: '5',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-17'),
    description: 'Netflix Subscription',
    category: 'Entertainment',
    amount: -15.99,
    type: 'debit',
  },
  {
    id: '6',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-16'),
    description: 'Electric Company',
    category: 'Utilities',
    amount: -145.67,
    type: 'debit',
  },
  {
    id: '7',
    accountId: '2',
    accountName: 'High Yield Savings',
    date: new Date('2025-11-15'),
    description: 'Transfer from Checking',
    category: 'Transfer',
    amount: 500.00,
    type: 'credit',
  },
  {
    id: '8',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-15'),
    description: 'Transfer to Savings',
    category: 'Transfer',
    amount: -500.00,
    type: 'debit',
  },
  {
    id: '9',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-15'),
    description: 'Chipotle',
    category: 'Dining',
    amount: -23.45,
    type: 'debit',
  },
  {
    id: '10',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-14'),
    description: 'Target',
    category: 'Shopping',
    amount: -156.78,
    type: 'debit',
  },
  {
    id: '11',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-14'),
    description: 'Starbucks',
    category: 'Dining',
    amount: -8.75,
    type: 'debit',
  },
  {
    id: '12',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-13'),
    description: 'CVS Pharmacy',
    category: 'Healthcare',
    amount: -34.22,
    type: 'debit',
  },
  {
    id: '13',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-12'),
    description: 'Uber',
    category: 'Transportation',
    amount: -18.50,
    type: 'debit',
  },
  {
    id: '14',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-12'),
    description: 'Movie Tickets',
    category: 'Entertainment',
    amount: -32.00,
    type: 'debit',
  },
  {
    id: '15',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-11'),
    description: 'Rent Payment',
    category: 'Housing',
    amount: -1850.00,
    type: 'debit',
  },
  {
    id: '16',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-10'),
    description: 'Trader Joes',
    category: 'Groceries',
    amount: -78.34,
    type: 'debit',
  },
  {
    id: '17',
    accountId: '3',
    accountName: 'Credit Card',
    date: new Date('2025-11-09'),
    description: 'Restaurant',
    category: 'Dining',
    amount: -65.43,
    type: 'debit',
  },
  {
    id: '18',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-08'),
    description: 'Gas Station',
    category: 'Transportation',
    amount: -45.00,
    type: 'debit',
  },
  {
    id: '19',
    accountId: '4',
    accountName: 'Investment Account',
    date: new Date('2025-11-05'),
    description: 'Dividend Payment',
    category: 'Income',
    amount: 234.56,
    type: 'credit',
  },
  {
    id: '20',
    accountId: '1',
    accountName: 'Primary Checking',
    date: new Date('2025-11-04'),
    description: 'Payroll Deposit',
    category: 'Income',
    amount: 3250.00,
    type: 'credit',
  },
];

export const mockBudgets: Budget[] = [
  {
    id: '1',
    category: 'Groceries',
    limit: 400,
    spent: 205.77,
    period: 'monthly',
  },
  {
    id: '2',
    category: 'Dining',
    limit: 250,
    spent: 97.63,
    period: 'monthly',
  },
  {
    id: '3',
    category: 'Transportation',
    limit: 200,
    spent: 115.84,
    period: 'monthly',
  },
  {
    id: '4',
    category: 'Entertainment',
    limit: 150,
    spent: 47.99,
    period: 'monthly',
  },
  {
    id: '5',
    category: 'Shopping',
    limit: 300,
    spent: 246.77,
    period: 'monthly',
  },
  {
    id: '6',
    category: 'Utilities',
    limit: 200,
    spent: 145.67,
    period: 'monthly',
  },
  {
    id: '7',
    category: 'Healthcare',
    limit: 150,
    spent: 34.22,
    period: 'monthly',
  },
  {
    id: '8',
    category: 'Housing',
    limit: 2000,
    spent: 1850.00,
    period: 'monthly',
  },
];

export const categories: TransactionCategory[] = [
  'Groceries',
  'Dining',
  'Transportation',
  'Entertainment',
  'Healthcare',
  'Shopping',
  'Utilities',
  'Housing',
  'Income',
  'Transfer',
  'Other',
];
